package com.tracker.expense.db.model;
// Generated Oct 3, 2019, 3:42:19 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name="grupo"
    ,catalog="expensetrackerdb"
)
public class Grupo  implements java.io.Serializable {


     private Integer idgrupo;
     private int version;
     private String nombre;
     private Set<GrupoArticulo> grupoArticulos = new HashSet<GrupoArticulo>(0);

    public Grupo() {
    }

	
    public Grupo(String nombre) {
        this.nombre = nombre;
    }
    public Grupo(String nombre, Set<GrupoArticulo> grupoArticulos) {
       this.nombre = nombre;
       this.grupoArticulos = grupoArticulos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idgrupo", unique=true, nullable=false)
    public Integer getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(Integer idgrupo) {
        this.idgrupo = idgrupo;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<GrupoArticulo> getGrupoArticulos() {
        return this.grupoArticulos;
    }
    
    public void setGrupoArticulos(Set<GrupoArticulo> grupoArticulos) {
        this.grupoArticulos = grupoArticulos;
    }




}


