package com.tracker.expense.db.model;
// Generated Oct 4, 2019, 4:41:45 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrupoArticuloId generated by hbm2java
 */
@Embeddable
public class GrupoArticuloId  implements java.io.Serializable {


     private int idgrupo;
     private int idarticulo;

    public GrupoArticuloId() {
    }

    public GrupoArticuloId(int idgrupo, int idarticulo) {
       this.idgrupo = idgrupo;
       this.idarticulo = idarticulo;
    }
   

    @Column(name="idgrupo", nullable=false)
    public int getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }

    @Column(name="idarticulo", nullable=false)
    public int getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GrupoArticuloId) ) return false;
		 GrupoArticuloId castOther = ( GrupoArticuloId ) other; 
         
		 return (this.getIdgrupo()==castOther.getIdgrupo())
 && (this.getIdarticulo()==castOther.getIdarticulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdgrupo();
         result = 37 * result + this.getIdarticulo();
         return result;
   }   


}


