package com.tracker.expense.db.model;
// Generated Oct 3, 2019, 1:28:57 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * GrupoArticulo generated by hbm2java
 */
@Entity
@Table(name="grupo_articulo"
    ,catalog="expensetrackerdb"
)
public class GrupoArticulo  implements java.io.Serializable {


     private GrupoArticuloId id;
     private int version;
     private Articulo articulo;
     private Grupo grupo;

    public GrupoArticulo() {
    }

    public GrupoArticulo(GrupoArticuloId id, Articulo articulo, Grupo grupo) {
       this.id = id;
       this.articulo = articulo;
       this.grupo = grupo;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idgrupo", column=@Column(name="idgrupo", nullable=false) ), 
        @AttributeOverride(name="idarticulo", column=@Column(name="idarticulo", nullable=false) ) } )
    public GrupoArticuloId getId() {
        return this.id;
    }
    
    public void setId(GrupoArticuloId id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idarticulo", nullable=false, insertable=false, updatable=false)
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idgrupo", nullable=false, insertable=false, updatable=false)
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }




}


